### ISSUE TITLE
Censorship causes Discord markup to bold

### ISSUE THREAD

**Issue by ferret99gt** [CQCumbers/dungeon_bot#1]
Would it be possible to add escape characters when the AI response includes *** censorship? Discord see this as markup and bolds the sentence if a second *** appears afterwards.

**Comment by CQCumbers** [comment]
Hopefully this has been fixed by 8224c1b

**Comment by ferret99gt** [comment]
It took a little bit to generate a "suitable" response but am reporting issue resolved.
